name = "MetropolisHastingsMCMC"
uuid = "dfc89a52-43ad-48d3-8d5a-1ecaf002c9fd"
version = "0.2.0"
authors = ["Nils Wildt, Andreas Scheidegger <andreas.scheidegger@eawag.ch>"]

[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
LogDensityProblems = "6fdf6af0-433a-55f7-b3ed-c6c6e0b8df7c"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
TestItems = "1c621080-faea-4a02-84b6-bbd5e436b8fe"

[compat]
ConcreteStructs = "0.2.3"
LogDensityProblems = "2"
ProgressMeter = "1"
julia = "1.6"
